export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_CREATE = 'COUNTER_CREATE';
export const COUNTER_UPDATE = 'COUNTER_UPDATE';
export const COUNTER_REMOVE = 'COUNTER_REMOVE';

export const UI_SET_DISPLAY_TYPE = 'UI_SET_DISPLAY_TYPE';
