export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_CREATE = 'COUNTER_CREATE';
export const COUNTER_UPDATE = 'COUNTER_UPDATE';
export const COUNTER_REMOVE = 'COUNTER_REMOVE';
export const COUNTER_REARRANGE = 'COUNTER_REARRANGE';

export const UI_SET_DISPLAY_TYPE = 'UI_SET_DISPLAY_TYPE';

export const STATISTICS_READ = 'STATISTICS_READ';

export const STATISTICS_INITIALIZE_SUCCESS = 'STATISTICS_INITIALIZE_SUCCESS';
export const STATISTICS_INITIALIZE_FAIL = 'STATISTICS_INITIALIZE_FAIL';
export const STATISTICS_WRITE_SUCCESS = 'STATISTICS_WRITE_SUCCESS';
export const STATISTICS_WRITE_FAIL = 'STATISTICS_WRITE_FAIL';
export const STATISTICS_READ_SUCCESS = 'STATISTICS_READ_SUCCESS';
export const STATISTICS_READ_FAIL = 'STATISTICS_READ_FAIL';
