export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_CREATE = 'COUNTER_CREATE';
export const COUNTER_UPDATE = 'COUNTER_UPDATE';
export const COUNTER_SET_TITLE = 'COUNTER_SET_TITLE';
export const COUNTER_SET_IMAGE = 'COUNTER_ATTACH_IMAGE';
export const COUNTER_SET_COLOR = 'COUNTER_SET_COLOR';
export const COUNTER_SET_STEP = 'COUNTER_SET_STEP';
export const COUNTER_REMOVE = 'COUNTER_REMOVE';

export const UI_SET_DISPLAY_TYPE = 'UI_SET_DISPLAY_TYPE';
